import { readFileSync } from "node:fs";
import { join } from "node:path";
import Link from "next/link";
import { site, coreAreas, hospitals } from "@/config/site";
import { ArrowRightIcon } from "@/components/ui/Icons";
import { ServiceMapInteractive } from "./ServiceMapInteractive";

/*
 * "Where we drive": the service-area map on a navy ground.
 *
 * The map is generated by `scripts/build-map.ts` (npm run build:map) into
 * public/brand/service-map.svg and inlined here at build time so it paints
 * with the page, needs no JS and picks up the page's fonts. The real,
 * crawlable content is the <nav> of city links beside it; the SVG is
 * decorative for assistive tech and gets one plain-language description.
 */
const svgMarkup = readFileSync(join(process.cwd(), "public/brand/service-map.svg"), "utf8")
  .replace(/^\s*<\?xml[^>]*\?>\s*/, "")
  .trim();

const mapDescription =
  "Map of north Houston showing Northline's service area: Houston, Spring, Humble, The Woodlands and Cypress, with the hospitals we drive to.";

export function AreasPreview() {
  const cities = coreAreas.map((a) => ({
    slug: a.slug,
    name: a.name,
    hospitals: hospitals.filter((h) => h.nearestAreas.includes(a.slug)).length,
  }));

  return (
    <section id="areas" aria-labelledby="areas-heading" className="bg-navy on-dark py-12 text-cream sm:py-20 lg:py-24">
      <div className="container-page">
        <p className="label mb-3 text-cream">Where we drive</p>
        <h2 id="areas-heading" className="max-w-3xl text-[2rem] font-bold !text-white sm:text-[2.5rem]">
          Wheelchair van rides across north Houston
        </h2>
        <p className="mt-4 max-w-3xl text-lg text-cream/85">
          We pick up across the north side and drive anywhere in the Houston area, including the Texas Medical Center.
        </p>

        <div className="mt-10 grid gap-10 xl:grid-cols-[minmax(0,1fr)_18rem] xl:items-start xl:gap-12">
          {/* Phones: a static, lazy image of the same map; the interactive map is desktop-only. */}
          {/* eslint-disable-next-line @next/next/no-img-element -- a static SVG; next/image adds nothing here */}
          <img
            data-service-map-static
            src="/brand/service-map.svg"
            alt={mapDescription}
            width={1200}
            height={900}
            loading="lazy"
            decoding="async"
            className="-mx-4 block h-auto w-[calc(100%+2rem)] max-w-none sm:mx-0 sm:w-full sm:rounded-[var(--radius-card)] lg:hidden"
          />
          <div className="relative hidden lg:block lg:max-w-[1200px]">
            <div
              data-service-map
              role="img"
              aria-label={mapDescription}
              className="relative overflow-hidden sm:rounded-[var(--radius-card)]"
              dangerouslySetInnerHTML={{ __html: svgMarkup }}
            />
            <ServiceMapInteractive cities={cities} />
          </div>

          <nav aria-label="Service area" className="xl:pt-2">
            <ul className="flex flex-col divide-y divide-cream/15">
              {coreAreas.map((a) => (
                <li key={a.slug}>
                  <Link
                    href={`/service-area/${a.slug}`}
                    data-area-link={a.slug}
                    className="flex min-h-12 items-center py-2 text-lg font-bold text-cream underline decoration-cream/50 underline-offset-4 hover:decoration-cream"
                  >
                    {a.name} wheelchair transportation
                  </Link>
                </li>
              ))}
            </ul>
            <p className="mt-6 text-cream/85">Also serving {site.moreAreas.join(", ")} and more.</p>
            <Link
              href="/service-area"
              className="mt-3 inline-flex min-h-12 items-center gap-2 font-bold text-cream underline decoration-cream/50 underline-offset-4 hover:decoration-cream"
            >
              See the full service area <ArrowRightIcon />
            </Link>
          </nav>
        </div>
      </div>
    </section>
  );
}
